In [2]:
!pip install pandas

Collecting pandas
  Downloading pandas-2.3.3-cp39-cp39-macosx_11_0_arm64.whl (10.8 MB)
     |████████████████████████████████| 10.8 MB 10.0 MB/s eta 0:00:01
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/seoyeonkim/customs-rag/.venv/lib/python3.9/site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1
  Downloading pytz-2026.2-py2.py3-none-any.whl (510 kB)
     |████████████████████████████████| 510 kB 1.1 MB/s eta 0:00:01
Collecting numpy>=1.22.4
  Downloading numpy-2.0.2-cp39-cp39-macosx_14_0_arm64.whl (5.3 MB)
     |████████████████████████████████| 5.3 MB 13.6 MB/s eta 0:00:01
Collecting tzdata>=2022.7
  Downloading tzdata-2026.2-py2.py3-none-any.whl (349 kB)
     |████████████████████████████████| 349 kB 9.8 MB/s eta 0:00:01
Requirement already satisfied: six>=1.5 in /Users/seoyeonkim/customs-rag/.venv/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Installing collected packages: tzdata, pytz, numpy, pandas
Successfully installed numpy-2.0.2 pandas-2.3.3 pytz-2026.2 tzdata-2026.2
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Users/seoyeonkim/customs-rag/.venv/bin/python3 -m pip install --upgrade pip' command.

In [30]:
#PDF 로드

import fitz
import re
import pandas as pd

pdf_path = "../data/fta-cn/psr_kor.pdf"

doc = fitz.open(pdf_path)

all_text = ""

for page in doc:
    all_text += page.get_text()

print("총 글자수:", len(all_text))

총 글자수: 514739

In [32]:
#HS 코드 위치 찾기

pattern = r"\d{4}\.\d{2}"

matches = list(re.finditer(pattern, all_text))

print("HS 코드 개수:", len(matches))

for m in matches[:10]:
    print(m.group())

HS 코드 개수: 5247
0101.21
0101.29
0101.30
0101.90
0102.21
0102.29
0102.31
0102.39
0102.90
0103.10

In [33]:
#chunk 생성

chunks = []

for i in range(len(matches)):

    start = matches[i].start()

    if i < len(matches) - 1:
        end = matches[i + 1].start()
    else:
        end = len(all_text)

    hs_code = matches[i].group()

    content = all_text[start:end].strip()

    chunks.append({
        "hs_code": hs_code,
        "content": content
    })

print("생성된 chunk 수:", len(chunks))

생성된 chunk 수: 5247

In [34]:
#확인

chunks[0]

{'hs_code': '0101.21', 'content': '0101.21 \n번식용 \n완전생산기준'}

In [35]:
print(len(chunks))

for i in range(20):
    print(chunks[i]["hs_code"])
    print(chunks[i]["content"][:200])
    print("="*50)

5247
0101.21
0101.21
번식용
완전생산기준
==================================================
0101.29
0101.29
기타
완전생산기준
==================================================
0101.30
0101.30
당나귀
완전생산기준
==================================================
0101.90
0101.90
기타
완전생산기준

01.02

살아 있는 소




축우(畜牛)
==================================================
0102.21
0102.21
번식용
완전생산기준
==================================================
0102.29
0102.29
기타
완전생산기준



버팔로
==================================================
0102.31
0102.31
번식용
완전생산기준
==================================================
0102.39
0102.39
기타
완전생산기준
==================================================
0102.90
0102.90
기타
완전생산기준

01.03

살아 있는 돼지
==================================================
0103.10
0103.10
번식용
완전생산기준



기타
==================================================
0103.91
0103.91
중량이 50 킬로그램 미만인 것
완전생산기준
==================================================
0103.92
0103.92
중량이 50 킬로그램 이상인 것
완전생산기준

37-2

류
호
소호
(HS 2012)
품목명
적용가능한
품목별 원산지 규정

01.04

살아 있는 면양과 산양
==================================================
0104.10
0104.10
면양
완전생산기준
==================================================
0104.20
0104.20
산양
완전생산기준

01.05

살아 있는 가금(家禽)류[닭(갈루스
도메스티쿠스(Gallus domesticus)
종으로 한정한다)ㆍ오리ㆍ거위ㆍ
칠면조와 기니아새로 한정한다]




중량이 185 그램 이하인 것
==================================================
0105.11
0105.11
닭[갈루스 도메스티쿠스(Gallus domesticus)
종으로 한정한다]
완전생산기준
==================================================
0105.12
0105.12
칠면조
완전생산기준
==================================================
0105.13
0105.13
오리
완전생산기준
==================================================
0105.14
0105.14
거위
완전생산기준
==================================================
0105.15
0105.15
기니아새
완전생산기준



기타
==================================================
0105.94
0105.94
닭[갈루스 도메스티쿠스(Gallus domesticus)
종으로 한정한다]
완전생산기준
==================================================

In [36]:
lines = all_text.split("\n")

for line in lines[:300]:
    print(repr(line))

' '
'37-1 '
' '
'제 2 부 - 품목별 원산지 규정 '
'류 '
'호 '
'소호 '
'(HS 2012) '
'품목명 '
'적용가능한 '
'품목별 원산지 규정 '
'제1 부 살아 있는 '
'동물과 동물성 생산품 '
'  '
'  '
'01 '
' '
' '
'제1 류 살아 있는 동물 '
' '
' '
'01.01 '
' '
'살아 있는 말ㆍ당나귀ㆍ노새와 버새 '
' '
' '
' '
' '
'말 '
' '
' '
' '
'0101.21 '
'번식용 '
'완전생산기준 '
' '
' '
'0101.29 '
'기타 '
'완전생산기준 '
' '
' '
'0101.30 '
'당나귀 '
'완전생산기준 '
' '
' '
'0101.90 '
'기타 '
'완전생산기준 '
' '
'01.02 '
' '
'살아 있는 소 '
' '
' '
' '
' '
'축우(畜牛) '
' '
' '
' '
'0102.21 '
'번식용 '
'완전생산기준 '
' '
' '
'0102.29 '
'기타 '
'완전생산기준 '
' '
' '
' '
'버팔로 '
' '
' '
' '
'0102.31 '
'번식용 '
'완전생산기준 '
' '
' '
'0102.39 '
'기타 '
'완전생산기준 '
' '
' '
'0102.90 '
'기타 '
'완전생산기준 '
' '
'01.03 '
' '
'살아 있는 돼지 '
' '
' '
' '
'0103.10 '
'번식용 '
'완전생산기준 '
' '
' '
' '
'기타 '
' '
' '
' '
'0103.91 '
'중량이 50 킬로그램 미만인 것 '
'완전생산기준 '
' '
' '
'0103.92 '
'중량이 50 킬로그램 이상인 것 '
'완전생산기준 '
' '
'37-2 '
' '
'류 '
'호 '
'소호 '
'(HS 2012) '
'품목명 '
'적용가능한 '
'품목별 원산지 규정 '
' '
'01.04 '
' '
'살아 있는 면양과 산양 '
' '
' '
' '
'0104.10 '
'면양 '
'완전생산기준 '
' '
' '
'0104.20 '
'산양 '
'완전생산기준 '
' '
'01.05 '
' '
'살아 있는 가금(家禽)류[닭(갈루스 '
'도메스티쿠스(Gallus domesticus) '
'종으로 한정한다)ㆍ오리ㆍ거위ㆍ '
'칠면조와 기니아새로 한정한다] '
' '
' '
' '
' '
'중량이 185 그램 이하인 것 '
' '
' '
' '
'0105.11 '
'닭[갈루스 도메스티쿠스(Gallus domesticus) '
'종으로 한정한다] '
'완전생산기준 '
' '
' '
'0105.12 '
'칠면조 '
'완전생산기준 '
' '
' '
'0105.13 '
'오리 '
'완전생산기준 '
' '
' '
'0105.14 '
'거위 '
'완전생산기준 '
' '
' '
'0105.15 '
'기니아새 '
'완전생산기준 '
' '
' '
' '
'기타 '
' '
' '
' '
'0105.94 '
'닭[갈루스 도메스티쿠스(Gallus domesticus) '
'종으로 한정한다] '
'완전생산기준 '
' '
' '
'0105.99 '
'기타 '
'완전생산기준 '
' '
'01.06 '
' '
'그 밖의 살아 있는 동물 '
' '
' '
' '
' '
'포유동물 '
' '
' '
' '
'0106.11 '
'영장류 '
'완전생산기준 '
' '
' '
'0106.12 '
'고래와 돌고래류(고래목의 포유동물), '
'바다소(바다소목의 포유동물), 물개ㆍ '
'바다사자와 바다코끼리(기각아목의 '
'포유동물) '
'완전생산기준 '
' '
' '
'0106.13 '
'낙타와 그 밖의 낙타과의 동물 '
'[카멜리대(camelidae)과] '
'완전생산기준 '
' '
'37-3 '
' '
'류 '
'호 '
'소호 '
'(HS 2012) '
'품목명 '
'적용가능한 '
'품목별 원산지 규정 '
' '
' '
'0106.14 '
'토끼 '
'완전생산기준 '
' '
' '
'0106.19 '
'기타 '
'완전생산기준 '
' '
' '
'0106.20 '
'파충류(뱀과 거북을 포함한다) '
'완전생산기준 '
' '
' '
' '
'조류 '
' '
' '
' '
'0106.31 '
'맹금류 '
'완전생산기준 '
' '
' '
'0106.32 '
'앵무류[패럿류(parrots)ㆍ패러키트류 '
'(parakeets)ㆍ금강앵무류 및 '
'유황앵무류를 포함한다] '
'완전생산기준 '
' '
' '
'0106.33 '
'타조와 에뮤(emus) [드로마이어스 '
'노배홀란디애(Dromaius novaehollandiae)] '
'완전생산기준 '
' '
' '
'0106.39 '
'기타 '
'완전생산기준 '
' '
' '
' '
'곤충류 '
' '
' '
' '
'0106.41 '
'벌 '
'완전생산기준 '
' '
' '
'0106.49 '
'기타 '
'완전생산기준 '
' '
' '
'0106.90 '
'기타 '
'완전생산기준 '
'02 '
' '
' '

In [37]:
import re

def is_psr_code(line):
    line = line.strip()

    patterns = [
    r'^\d{4}$',
    r'^\d{4}\.\d{2}$',
    r'^\d{4}\s*[-–]\s*\d{4}$',
    r'^\d{4}\.\d{2}\s*[-–]\s*\d{4}\.\d{2}$',
    r'^\d{4}\s*[-–]\s*\d{4}\.\d{2}$',
]

    return any(re.match(p, line) for p in patterns)

In [38]:
lines = all_text.split("\n")

for line in lines:
    if is_psr_code(line):
        print(line)

0101.21
0101.29
0101.30
0101.90
0102.21
0102.29
0102.31
0102.39
0102.90
0103.10
0103.91
0103.92
0104.10
0104.20
0105.11
0105.12
0105.13
0105.14
0105.15
0105.94
0105.99
0106.11
0106.12
0106.13
0106.14
0106.19
0106.20
0106.31
0106.32
0106.33
0106.39
0106.41
0106.49
0106.90
0201.10
0201.20
0201.30
0202.10
0202.20
0202.30
0203.11
0203.12
0203.19
0203.21
0203.22
0203.29
0204.10
0204.21
0204.22
0204.23
0204.30
0204.41
0204.42
0204.43
0204.50
0205.00
0206.10
0206.21
0206.22
0206.29
0206.30
0206.41
0206.49
0206.80
0206.90
0207.11
0207.12
0207.13
0207.14
0207.24
0207.25
0207.26
0207.27
0207.41
0207.42
0207.43
0207.44
0207.45
0207.51
0207.52
0207.53
0207.54
0207.55
0207.60
0208.10
0208.30
0208.40
0208.50
0208.60
0208.90
0209.10
0209.90
0210.11
0210.12
0210.19
0210.20
0210.91
0210.92
0210.93
0210.99
0301.11
0301.19
0301.91
0301.92
0301.93
0301.94
0301.95
0301.99
0302.11
0302.13
0302.14
0302.19
0302.21
0302.22
0302.23
0302.24
0302.29
0302.31
0302.32
0302.33
0302.34
0302.35
0302.36
0302.39
0302.41
0302.42
0302.43
0302.44
0302.45
0302.46
0302.47
0302.51
0302.52
0302.53
0302.54
0302.55
0302.56
0302.59
0302.71
0302.72
0302.73
0302.74
0302.79
0302.81
0302.82
0302.83
0302.84
0302.85
0302.89
0302.90
0303.11
0303.12
0303.13
0303.14
0303.19
0303.23
0303.24
0303.25
0303.26
0303.29
0303.31
0303.32
0303.33
0303.34
0303.39
0303.41
0303.42
0303.43
0303.44
0303.45
0303.46
0303.49
0303.51
0303.53
0303.54
0303.55
0303.56
0303.57
0303.63
0303.64
0303.65
0303.66
0303.67
0303.68
0303.69
0303.81
0303.82
0303.83
0303.84
0303.89
0303.90
0304.31
0304.32
0304.33
0304.39
0304.41
0304.42
0304.43
0304.44
0304.45
0304.46
0304.49
0304.51
0304.52
0304.53
0304.54
0304.55
0304.59
0304.61
0304.62
0304.63
0304.69
0304.71
0304.72
0304.73
0304.74
0304.75
0304.79
0304.81
0304.82
0304.83
0304.84
0304.85
0304.86
0304.87
0304.89
0304.91
0304.92
0304.93
0304.94
0304.95
0304.99
0305.10
0305.20
0305.31
0305.32
0305.39
0305.41
0305.42
0305.43
0305.44
0305.49
0305.51
0305.59
0305.61
0305.62
0305.63
0305.64
0305.69
0305.71
0305.72
0305.79
0306.11
0306.12
0306.14
0306.15
0306.16
0306.17
0306.19
0306.21
0306.22
0306.24
0306.25
0306.26
0306.27
0306.29
0307.11
0307.19
0307.21
0307.29
0307.31
0307.39
0307.41
0307.49
0307.51
0307.59
0307.60
0307.71
0307.79
0307.81
0307.89
0307.91
0307.99
0308.11
0308.19
0308.21
0308.29
0308.30
0308.90
0401.10
0401.20
0401.40
0401.50
0402.10
0402.21
0402.29
0402.91
0402.99
0403.10
0403.90
0404.10
0404.90
0405.10
0405.20
0405.90
0406.10
0406.20
0406.30
0406.40
0406.90
0407.11
0407.19
0407.21
0407.29
0407.90
0408.11
0408.19
0408.91
0408.99
0409.00
0410.00
0501.00
0502.10
0502.90
0504.00
0505.10
0505.90
0506.10
0506.90
0507.10
0507.90
0508.00
0510.00
0511.10
0511.91
0511.99
0601.10
0601.20
0602.10
0602.20
0602.30
0602.40
0602.90
0603.11
0603.12
0603.13
0603.14
0603.15
0603.19
0603.90
0604.20
0604.90
0701.10
0701.90
0702.00
0703.10
0703.20
0703.90
0704.10
0704.20
0704.90
0705.11
0705.19
0705.21
0705.29
0706.10
0706.90
0707.00
0708.10
0708.20
0708.90
0709.20
0709.30
0709.40
0709.51
0709.59
0709.60
0709.70
0709.91
0709.92
0709.93
0709.99
0710.10
0710.21
0710.22
0710.29
0710.30
0710.40
0710.80
0710.90
0711.20
0711.40
0711.51
0711.59
0711.90
0712.20
0712.31
0712.32
0712.33
0712.39
0712.90
0713.10
0713.20
0713.31
0713.32
0713.33
0713.34
0713.35
0713.39
0713.40
0713.50
0713.60
0713.90
0714.10
0714.20
0714.30
0714.40
0714.50
0714.90
0801.11
0801.12
0801.19
0801.21
0801.22
0801.31
0801.32
0802.11
0802.12
0802.21
0802.22
0802.31
0802.32
0802.41
0802.42
0802.51
0802.52
0802.61
0802.62
0802.70
0802.80
0802.90
0803.10
0803.90
0804.10
0804.20
0804.30
0804.40
0804.50
0805.10
0805.20
0805.40
0805.50
0805.90
0806.10
0806.20
0807.11
0807.19
0807.20
0808.10
0808.30
0808.40
0809.10
0809.21
0809.29
0809.30
0809.40
0810.10
0810.20
0810.30
0810.40
0810.50
0810.60
0810.70
0810.90
0811.10
0811.20
0811.90
0812.10
0812.90
0813.10
0813.20
0813.30
0813.40
0813.50
0814.00
0901.11
0901.12
0901.21
0901.22
0901.90
0902.10
0902.20
0902.30
0902.40
0903.00
0904.11
0904.12
0904.21
0904.22
0905.10
0905.20
0906.11
0906.19
0906.20
0907.10
0907.20
0908.11
0908.12
0908.21
0908.22
0908.31
0908.32
0909.21
0909.22
0909.31
0909.32
0909.61
0909.62
0910.11
0910.12
0910.20
0910.30
0910.91
0910.99
1001.11
1001.19
1001.91
1001.99
1002.10
1002.90
1003.10
1003.90
1004.10
1004.90
1005.10
1005.90
1006.10
1006.20
1006.30
1006.40
1007.10
1007.90
1008.10
1008.21
1008.29
1008.30
1008.40
1008.50
1008.60
1008.90
1101.00
1102.20
1102.90
1103.11
1103.13
1103.19
1103.20
1104.12
1104.19
1104.22
1104.23
1104.29
1104.30
1105.10
1105.20
1106.10
1106.20
1106.30
1107.10
1107.20
1108.11
1108.12
1108.13
1108.14
1108.19
1108.20
1109.00
1201.10
1201.90
1202.30
1202.41
1202.42
1203.00
1204.00
1205.10
1205.90
1206.00
1207.10
1207.21
1207.29
1207.30
1207.40
1207.50
1207.60
1207.70
1207.91
1207.99
1208.10
1208.90
1209.10
1209.21
1209.22
1209.23
1209.24
1209.25
1209.29
1209.30
1209.91
1209.99
1210.10
1210.20
1211.20
1211.30
1211.40
1211.90
1212.21
1212.29
1212.91
1212.92
1212.93
1212.94
1212.99
1213.00
1214.10
1214.90
1301.20
1301.90
1302.11
1302.12
1302.13
1302.19
1302.20
1302.31
1302.32
1302.39
1401.10
1401.20
1401.90
1404.20
1404.90
1501.10
1501.20
1501.90
1502.10
1502.90
1503.00
1504.10
1504.20
1504.30
1505.00
1506.00
1507.10
1507.90
1508.10
1508.90
1509.10
1509.90
1510.00
1511.10
1511.90
1512.11
1512.19
1512.21
1512.29
1513.11
1513.19
1513.21
1513.29
1514.11
1514.19
1514.91
1514.99
1515.11
1515.19
1515.21
1515.29
1515.30
1515.50
1515.90
1516.10
1516.20
1517.10
1517.90
1518.00
1520.00
1521.10
1521.90
1522.00
1601.00
1602.10
1602.20
1602.31
1602.32
1602.39
1602.41
1602.42
1602.49
1602.50
1602.90
1603.00
1604.11
1604.12
1604.13
1604.14
1604.15
1604.16
1604.17
1604.19
1604.20
1604.31
1604.32
1605.10
1605.21
1605.29
1605.30
1605.40
1605.51
1605.52
1605.53
1605.54
1605.55
1605.56
1605.57
1605.58
1605.59
1605.61
1605.62
1605.63
1605.69
1701.12
1701.13
1701.14
1701.91
1701.99
1702.11
1702.19
1702.20
1702.30
1702.40
1702.50
1702.60
1702.90
1703.10
1703.90
1704.10
1704.90
1801.00
1802.00
1803.10
1803.20
1804.00
1805.00
1806.10
1806.20
1806.31
1806.32
1806.90
1901.10
1901.20
1901.90
1902.11
1902.19
1902.20
1902.30
1902.40
1903.00
1904.10
1904.20
1904.30
1904.90
1905.10
1905.20
1905.31
1905.32
1905.40
1905.90
2001.10
2001.90
2002.10
2002.90
2003.10
2003.90
2004.10
2004.90
2005.10
2005.20
2005.40
2005.51
2005.59
2005.60
2005.70
2005.80
2005.91
2005.99
2006.00
2007.10
2007.91
2007.99
2008.11
2008.19
2008.20
2008.30
2008.40
2008.50
2008.60
2008.70
2008.80
2008.91
2008.93
2008.97
2008.99
2009.11
2009.12
2009.19
2009.21
2009.29
2009.31
2009.39
2009.41
2009.49
2009.50
2009.61
2009.69
2009.71
2009.79
2009.81
2009.89
2009.90
2101.11
2101.12
2101.20
2101.30
2102.10
2102.20
2102.30
2103.10
2103.20
2103.30
2103.90
2104.10
2104.20
2105.00
2106.10
2106.90
2201.10
2201.90
2202.10
2202.90
2203.00
2204.10
2204.21
2204.29
2204.30
2205.10
2205.90
2206.00
2207.10
2207.20
2208.20
2208.30
2208.40
2208.50
2208.60
2208.70
2208.90
2209.00
2301.10
2301.20
2302.10
2302.30
2302.40
2302.50
2303.10
2303.20
2303.30
2304.00
2305.00
2306.10
2306.20
2306.30
2306.41
2306.49
2306.50
2306.60
2306.90
2307.00
2308.00
2309.10
2309.90
2401.10
2401.20
2401.30
2402.10
2402.20
2402.90
2403.11
2403.19
2403.91
2403.99
2501.00
2502.00
2503.00
2504.10
2504.90
2505.10
2505.90
2506.10
2506.20
2507.00
2508.10
2508.30
2508.40
2508.50
2508.60
2508.70
2509.00
2510.10
2510.20
2511.10
2511.20
2512.00
2513.10
2513.20
2514.00
2515.11
2515.12
2515.20
2516.11
2516.12
2516.20
2516.90
2517.10
2517.20
2517.30
2517.41
2517.49
2518.10
2518.20
2518.30
2519.10
2519.90
2520.10
2520.20
2521.00
2522.10
2522.20
2522.30
2523.10
2523.21
2523.29
2523.30
2523.90
2524.10
2524.90
2525.10
2525.20
2525.30
2526.10
2526.20
2528.00
2529.10
2529.21
2529.22
2529.30
2530.10
2530.20
2530.90
2601.11
2601.12
2601.20
2602.00
2603.00
2604.00
2605.00
2606.00
2607.00
2608.00
2609.00
2610.00
2611.00
2612.10
2612.20
2613.10
2613.90
2614.00
2615.10
2615.90
2616.10
2616.90
2617.10
2617.90
2618.00
2619.00
2620.11
2620.19
2620.21
2620.29
2620.30
2620.40
2620.60
2620.91
2620.99
2621.10
2621.90
2701.11
2701.12
2701.19
2701.20
2702.10
2702.20
2703.00
2704.00
2705.00
2706.00
2707.10
2707.20
2707.30
2707.40
2707.50
2707.91
2707.99
2708.10
2708.20
2709.00
2710.12
2710.19
2710.20
2710.91
2710.99
2711.11
2711.12
2711.13
2711.14
2711.19
2711.21
2711.29
2712.10
2712.20
2712.90
2713.11
2713.12
2713.20
2713.90
2714.10
2714.90
2715.00
2716.00
2801.10
2801.20
2801.30
2802.00
2803.00
2804.10
2804.21
2804.29
2804.30
2804.40
2804.50
2804.61
2804.69
2804.70
2804.80
2804.90
2805.11
2805.12
2805.19
2805.30
2805.40
2806.10
2806.20
2807.00
2808.00
2809.10
2809.20
2810.00
2811.11
2811.19
2811.21
2811.22
2811.29
2812.10
2812.90
2813.10
2813.90
2814.10
2814.20
2815.11
2815.12
2815.20
2815.30
2816.10
2816.40
2817.00
2818.10
2818.20
2818.30
2819.10
2819.90
2820.10
2820.90
2821.10
2821.20
2822.00
2823.00
2824.10
2824.90
2825.10
2825.20
2825.30
2825.40
2825.50
2825.60
2825.70
2825.80
2825.90
2826.12
2826.19
2826.30
2826.90
2827.10
2827.20
2827.31
2827.32
2827.35
2827.39
2827.41
2827.49
2827.51
2827.59
2827.60
2828.10
2828.90
2829.11
2829.19
2829.90
2830.10
2830.90
2831.10
2831.90
2832.10
2832.20
2832.30
2833.11
2833.19
2833.21
2833.22
2833.24
2833.25
2833.27
2833.29
2833.30
2833.40
2834.10
2834.21
2834.29
2835.10
2835.22
2835.24
2835.25
2835.26
2835.29
2835.31
2835.39
2836.20
2836.30
2836.40
2836.50
2836.60
2836.91
2836.92
2836.99
2837.11
2837.19
2837.20
2839.11
2839.19
2839.90
2840.11
2840.19
2840.20
2840.30
2841.30
2841.50
2841.61
2841.69
2841.70
2841.80
2841.90
2842.10
2842.90
2843.10
2843.21
2843.29
2843.30
2843.90
2844.10
2844.20
2844.30
2844.40
2844.50
2845.10
2845.90
2846.10
2846.90
2847.00
2848.00
2849.10
2849.20
2849.90
2850.00
2852.10
2852.90
2853.00
2901.10
2901.21
2901.22
2901.23
2901.24
2901.29
2902.11
2902.19
2902.20
2902.30
2902.41
2902.42
2902.43
2902.44
2902.50
2902.60
2902.70
2902.90
2903.11
2903.12
2903.13
2903.14
2903.15
2903.19
2903.21
2903.22
2903.23
2903.29
2903.31
2903.39
2903.71
2903.72
2903.73
2903.74
2903.75
2903.76
2903.77
2903.78
2903.79
2903.81
2903.82
2903.89
2903.91
2903.92
2903.99
2904.10
2904.20
2904.90
2905.11
2905.12
2905.13
2905.14
2905.16
2905.17
2905.19
2905.22
2905.29
2905.31
2905.32
2905.39
2905.41
2905.42
2905.43
2905.44
2905.45
2905.49
2905.51
2905.59
2906.11
2906.12
2906.13
2906.19
2906.21
2906.29
2907.11
2907.12
2907.13
2907.15
2907.19
2907.21
2907.22
2907.23
2907.29
2908.11
2908.19
2908.91
2908.92
2908.99
2909.11
2909.19
2909.20
2909.30
2909.41
2909.43
2909.44
2909.49
2909.50
2909.60
2910.10
2910.20
2910.30
2910.40
2910.90
2911.00
2912.11
2912.12
2912.19
2912.21
2912.29
2912.41
2912.42
2912.49
2912.50
2912.60
2913.00
2914.11
2914.12
2914.13
2914.19
2914.22
2914.23
2914.29
2914.31
2914.39
2914.40
2914.50
2914.61
2914.69
2914.70
2915.11
2915.12
2915.13
2915.21
2915.24
2915.29
2915.31
2915.32
2915.33
2915.36
2915.39
2915.40
2915.50
2915.60
2915.70
2915.90
2916.11
2916.12
2916.13
2916.14
2916.15
2916.16
2916.19
2916.20
2916.31
2916.32
2916.34
2916.39
2917.11
2917.12
2917.13
2917.14
2917.19
2917.20
2917.32
2917.33
2917.34
2917.35
2917.36
2917.37
2917.39
2918.11
2918.12
2918.13
2918.14
2918.15
2918.16
2918.18
2918.19
2918.21
2918.22
2918.23
2918.29
2918.30
2918.91
2918.99
2919.10
2919.90
2920.11
2920.19
2920.90
2921.11
2921.19
2921.21
2921.22
2921.29
2921.30
2921.41
2921.42
2921.43
2921.44
2921.45
2921.46
2921.49
2921.51
2921.59
2922.11
2922.12
2922.13
2922.14
2922.19
2922.21
2922.29
2922.31
2922.39
2922.41
2922.42
2922.43
2922.44
2922.49
2922.50
2923.10
2923.20
2923.90
2924.11
2924.12
2924.19
2924.21
2924.23
2924.24
2924.29
2925.11
2925.12
2925.19
2925.21
2925.29
2926.10
2926.20
2926.30
2926.90
2927.00
2928.00
2929.10
2929.90
2930.20
2930.30
2930.40
2930.50
2930.90
2931.10
2931.20
2931.90
2932.11
2932.12
2932.13
2932.19
2932.20
2932.91
2932.92
2932.93
2932.94
2932.95
2932.99
2933.11
2933.19
2933.21
2933.29
2933.31
2933.32
2933.33
2933.39
2933.41
2933.49
2933.52
2933.53
2933.54
2933.55
2933.59
2933.61
2933.69
2933.71
2933.72
2933.79
2933.91
2933.99
2934.10
2934.20
2934.30
2934.91
2934.99
2935.00
2936.21
2936.22
2936.23
2936.24
2936.25
2936.26
2936.27
2936.28
2936.29
2936.90
2937.11
2937.12
2937.19
2937.21
2937.22
2937.23
2937.29
2937.50
2937.90
2938.10
2938.90
2939.11
2939.19
2939.20
2939.30
2939.41
2939.42
2939.43
2939.44
2939.49
2939.51
2939.59
2939.61
2939.62
2939.63
2939.69
2939.91
2939.99
2940.00
2941.10
2941.20
2941.30
2941.40
2941.50
2941.90
2942.00
3001.20
3001.90
3002.10
3002.20
3002.30
3002.90
3003.10
3003.20
3003.31
3003.39
3003.40
3003.90
3004.10
3004.20
3004.31
3004.32
3004.39
3004.40
3004.50
3004.90
3005.10
3005.90
3006.10
3006.20
3006.30
3006.40
3006.50
3006.60
3006.70
3006.91
3006.92
3101.00
3102.10
3102.21
3102.29
3102.30
3102.40
3102.50
3102.60
3102.80
3102.90
3103.10
3103.90
3104.20
3104.30
3104.90
3105.10
3105.20
3105.30
3105.40
3105.51
3105.59
3105.60
3105.90
3201.10
3201.20
3201.90
3202.10
3202.90
3203.00
3204.11
3204.12
3204.13
3204.14
3204.15
3204.16
3204.17
3204.19
3204.20
3204.90
3205.00
3206.11
3206.19
3206.20
3206.41
3206.42
3206.49
3206.50
3207.10
3207.20
3207.30
3207.40
3208.10
3208.20
3208.90
3209.10
3209.90
3210.00
3211.00
3212.10
3212.90
3213.10
3213.90
3214.10
3214.90
3215.11
3215.19
3215.90
3301.12
3301.13
3301.19
3301.24
3301.25
3301.29
3301.30
3301.90
3302.10
3302.90
3303.00
3304.10
3304.20
3304.30
3304.91
3304.99
3305.10
3305.20
3305.30
3305.90
3306.10
3306.20
3306.90
3307.10
3307.20
3307.30
3307.41
3307.49
3307.90
3401.11
3401.19
3401.20
3401.30
3402.11
3402.12
3402.13
3402.19
3402.20
3402.90
3403.11
3403.19
3403.91
3403.99
3404.20
3404.90
3405.10
3405.20
3405.30
3405.40
3405.90
3406.00
3407.00
3501.10
3501.90
3502.11
3502.19
3502.20
3502.90
3503.00
3504.00
3505.10
3505.20
3506.10
3506.91
3506.99
3507.10
3507.90
3601.00
3602.00
3603.00
3604.10
3604.90
3605.00
3606.10
3606.90
3701.10
3701.20
3701.30
3701.91
3701.99
3702.10
3702.31
3702.32
3702.39
3702.41
3702.42
3702.43
3702.44
3702.52
3702.53
3702.54
3702.55
3702.56
3702.96
3702.97
3702.98
3703.10
3703.20
3703.90
3704.00
3705.10
3705.90
3706.10
3706.90
3707.10
3707.90
3801.10
3801.20
3801.30
3801.90
3802.10
3802.90
3803.00
3804.00
3805.10
3805.90
3806.10
3806.20
3806.30
3806.90
3807.00
3808.50
3808.91
3808.92
3808.93
3808.94
3808.99
3809.10
3809.91
3809.92
3809.93
3810.10
3810.90
3811.11
3811.19
3811.21
3811.29
3811.90
3812.10
3812.20
3812.30
3813.00
3814.00
3815.11
3815.12
3815.19
3815.90
3816.00
3817.00
3818.00
3819.00
3820.00
3821.00
3822.00
3823.11
3823.12
3823.13
3823.19
3823.70
3824.10
3824.30
3824.40
3824.50
3824.60
3824.71
3824.72
3824.73
3824.74
3824.75
3824.76
3824.77
3824.78
3824.79
3824.81
3824.82
3824.83
3824.90
3825.10
3825.20
3825.30
3825.41
3825.49
3825.50
3825.61
3825.69
3825.90
3826.00
3901.10
3901.20
3901.30
3901.90
3902.10
3902.20
3902.30
3902.90
3903.11
3903.19
3903.20
3903.30
3903.90
3904.10
3904.21
3904.22
3904.30
3904.40
3904.50
3904.61
3904.69
3904.90
3905.12
3905.19
3905.21
3905.29
3905.30
3905.91
3905.99
3906.10
3906.90
3907.10
3907.20
3907.30
3907.40
3907.50
3907.60
3907.70
3907.91
3907.99
3908.10
3908.90
3909.10
3909.20
3909.30
3909.40
3909.50
3910.00
3911.10
3911.90
3912.11
3912.12
3912.20
3912.31
3912.39
3912.90
3913.10
3913.90
3914.00
3915.10
3915.20
3915.30
3915.90
3916.10
3916.20
3916.90
3917.10
3917.21
3917.22
3917.23
3917.29
3917.31
3917.32
3917.33
3917.39
3917.40
3918.10
3918.90
3919.10
3919.90
3920.10
3920.20
3920.30
3920.43
3920.49
3920.51
3920.59
3920.61
3920.62
3920.63
3920.69
3920.71
3920.73
3920.79
3920.91
3920.92
3920.93
3920.94
3920.99
3921.11
3921.12
3921.13
3921.14
3921.19
3921.90
3922.10
3922.20
3922.90
3923.10
3923.21
3923.29
3923.30
3923.40
3923.50
3923.90
3924.10
3924.90
3925.10
3925.20
3925.30
3925.90
3926.10
3926.20
3926.30
3926.40
3926.90
4001.10
4001.21
4001.22
4001.29
4001.30
4002.11
4002.19
4002.20
4002.31
4002.39
4002.41
4002.49
4002.51
4002.59
4002.60
4002.70
4002.80
4002.91
4002.99
4003.00
4004.00
4005.10
4005.20
4005.91
4005.99
4006.10
4006.90
4007.00
4008.11
4008.19
4008.21
4008.29
4009.11
4009.12
4009.21
4009.22
4009.31
4009.32
4009.41
4009.42
4010.11
4010.12
4010.19
4010.31
4010.32
4010.33
4010.34
4010.35
4010.36
4010.39
4011.10
4011.20
4011.30
4011.40
4011.50
4011.61
4011.62
4011.63
4011.69
4011.92
4011.93
4011.94
4011.99
4012.11
4012.12
4012.13
4012.19
4012.20
4012.90
4013.10
4013.20
4013.90
4014.10
4014.90
4015.11
4015.19
4015.90
4016.10
4016.91
4016.92
4016.93
4016.94
4016.95
4016.99
4017.00
4101.20
4101.50
4101.90
4102.10
4102.21
4102.29
4103.20
4103.30
4103.90
4104.11
4104.19
4104.41
4104.49
4105.10
4105.30
4106.21
4106.22
4106.31
4106.32
4106.40
4106.91
4106.92
4107.11
4107.12
4107.19
4107.91
4107.92
4107.99
4112.00
4113.10
4113.20
4113.30
4113.90
4114.10
4114.20
4115.10
4115.20
4201.00
4202.11
4202.12
4202.19
4202.21
4202.22
4202.29
4202.31
4202.32
4202.39
4202.91
4202.92
4202.99
4203.10
4203.21
4203.29
4203.30
4203.40
4205.00
4206.00
4301.10
4301.30
4301.60
4301.80
4301.90
4302.11
4302.19
4302.20
4302.30
4303.10
4303.90
4304.00
4401.10
4401.21
4401.22
4401.31
4401.39
4402.10
4402.90
4403.10
4403.20
4403.41
4403.49
4403.91
4403.92
4403.99
4404.10
4404.20
4405.00
4406.10
4406.90
4407.10
4407.21
4407.22
4407.25
4407.26
4407.27
4407.28
4407.29
4407.91
4407.92
4407.93
4407.94
4407.95
4407.99
4408.10
4408.31
4408.39
4408.90
4409.10
4409.21
4409.29
4410.11
4410.12
4410.19
4410.90
4411.12
4411.13
4411.14
4411.92
4411.93
4411.94
4412.10
4412.31
4412.32
4412.39
4412.94
4412.99
4413.00
4414.00
4415.10
4415.20
4416.00
4417.00
4418.10
4418.20
4418.40
4418.50
4418.60
4418.71
4418.72
4418.79
4418.90
4419.00
4420.10
4420.90
4421.10
4421.90
4501.10
4501.90
4502.00
4503.10
4503.90
4504.10
4504.90
4601.21
4601.22
4601.29
4601.92
4601.93
4601.94
4601.99
4602.11
4602.12
4602.19
4602.90
4701.00
4702.00
4703.11
4703.19
4703.21
4703.29
4704.11
4704.19
4704.21
4704.29
4705.00
4706.10
4706.20
4706.30
4706.91
4706.92
4706.93
4707.10
4707.20
4707.30
4707.90
4801.00
4802.10
4802.20
4802.40
4802.54
4802.55
4802.56
4802.57
4802.58
4802.61
4802.62
4802.69
4803.00
4804.11
4804.19
4804.21
4804.29
4804.31
4804.39
4804.41
4804.42
4804.49
4804.51
4804.52
4804.59
4805.11
4805.12
4805.19
4805.24
4805.25
4805.30
4805.40
4805.50
4805.91
4805.92
4805.93
4806.10
4806.20
4806.30
4806.40
4807.00
4808.10
4808.40
4808.90
4809.20
4809.90
4810.13
4810.14
4810.19
4810.22
4810.29
4810.31
4810.32
4810.39
4810.92
4810.99
4811.10
4811.41
4811.49
4811.51
4811.59
4811.60
4811.90
4812.00
4813.10
4813.20
4813.90
4814.20
4814.90
4816.20
4816.90
4817.10
4817.20
4817.30
4818.10
4818.20
4818.30
4818.50
4818.90
4819.10
4819.20
4819.30
4819.40
4819.50
4819.60
4820.10
4820.20
4820.30
4820.40
4820.50
4820.90
4821.10
4821.90
4822.10
4822.90
4823.20
4823.40
4823.61
4823.69
4823.70
4823.90
4901.10
4901.91
4901.99
4902.10
4902.90
4903.00
4904.00
4905.10
4905.91
4905.99
4906.00
4907.00
4908.10
4908.90
4909.00
4910.00
4911.10
4911.91
4911.99
5001.00
5002.00
5003.00
5004.00
5005.00
5006.00
5007.10
5007.20
5007.90
5101.11
5101.19
5101.21
5101.29
5101.30
5102.11
5102.19
5102.20
5103.10
5103.20
5103.30
5104.00
5105.10
5105.21
5105.29
5105.31
5105.39
5105.40
5106.10
5106.20
5107.10
5107.20
5108.10
5108.20
5109.10
5109.90
5110.00
5111.11
5111.19
5111.20
5111.30
5111.90
5112.11
5112.19
5112.20
5112.30
5112.90
5113.00
5201.00
5202.10
5202.91
5202.99
5203.00
5204.11
5204.19
5204.20
5205.11
5205.12
5205.13
5205.14
5205.15
5205.21
5205.22
5205.23
5205.24
5205.26
5205.27
5205.28
5205.31
5205.32
5205.33
5205.34
5205.35
5205.41
5205.42
5205.43
5205.44
5205.46
5205.47
5205.48
5206.11
5206.12
5206.13
5206.14
5206.15
5206.21
5206.22
5206.23
5206.24
5206.25
5206.31
5206.32
5206.33
5206.34
5206.35
5206.41
5206.42
5206.43
5206.44
5206.45
5207.10
5207.90
5208.11
5208.12
5208.13
5208.19
5208.21
5208.22
5208.23
5208.29
5208.31
5208.32
5208.33
5208.39
5208.41
5208.42
5208.43
5208.49
5208.51
5208.52
5208.59
5209.11
5209.12
5209.19
5209.21
5209.22
5209.29
5209.31
5209.32
5209.39
5209.41
5209.42
5209.43
5209.49
5209.51
5209.52
5209.59
5210.11
5210.19
5210.21
5210.29
5210.31
5210.32
5210.39
5210.41
5210.49
5210.51
5210.59
5211.11
5211.12
5211.19
5211.20

In [39]:
codes = []

for i, line in enumerate(lines):
    if is_psr_code(line):
        codes.append((i, line.strip()))

print("코드 수:", len(codes))
codes[:20]

코드 수: 5205

[(32, '0101.21'),
 (37, '0101.29'),
 (42, '0101.30'),
 (47, '0101.90'),
 (62, '0102.21'),
 (67, '0102.29'),
 (77, '0102.31'),
 (82, '0102.39'),
 (87, '0102.90'),
 (97, '0103.10'),
 (107, '0103.91'),
 (112, '0103.92'),
 (132, '0104.10'),
 (137, '0104.20'),
 (155, '0105.11'),
 (161, '0105.12'),
 (166, '0105.13'),
 (171, '0105.14'),
 (176, '0105.15'),
 (186, '0105.94')]

In [40]:
chunks = []

for idx in range(len(codes)):

    start_line = codes[idx][0]
    code = codes[idx][1]

    if idx < len(codes) - 1:
        end_line = codes[idx + 1][0]
    else:
        end_line = len(lines)

    content = "\n".join(lines[start_line:end_line])

    chunks.append({
        "code": code,
        "content": content
    })

print("chunk 수:", len(chunks))

chunk 수: 5205

In [41]:
chunks[30]

{'code': '0106.39',
 'content': '0106.39 \n기타 \n완전생산기준 \n \n \n \n곤충류 \n \n \n '}

In [42]:
for i in range(10):
    print("="*50)
    print(chunks[i]["code"])
    print(chunks[i]["content"][:300])

==================================================
0101.21
0101.21
번식용
완전생산기준


==================================================
0101.29
0101.29
기타
완전생산기준


==================================================
0101.30
0101.30
당나귀
완전생산기준


==================================================
0101.90
0101.90
기타
완전생산기준

01.02

살아 있는 소




축우(畜牛)



==================================================
0102.21
0102.21
번식용
완전생산기준


==================================================
0102.29
0102.29
기타
완전생산기준



버팔로



==================================================
0102.31
0102.31
번식용
완전생산기준


==================================================
0102.39
0102.39
기타
완전생산기준


==================================================
0102.90
0102.90
기타
완전생산기준

01.03

살아 있는 돼지



==================================================
0103.10
0103.10
번식용
완전생산기준



기타

In [43]:
print(chunks[20])
print(chunks[50])
print(chunks[100])

{'code': '0105.99', 'content': '0105.99 \n기타 \n완전생산기준 \n \n01.06 \n \n그 밖의 살아 있는 동물 \n \n \n \n \n포유동물 \n \n \n '}
{'code': '0204.30', 'content': '0204.30 \n어린 면양의 도체(屠體)와 이분도체 \n(二分屠體)(냉동한 것으로 한정한다) \n완전생산기준 \n \n \n \n그 밖의 면양의 고기(냉동한 것으로 \n한정한다) \n \n \n37-5 \n \n류 \n호 \n소호 \n(HS 2012) \n품목명 \n적용가능한 \n품목별 원산지 규정 \n \n '}
{'code': '0301.11', 'content': '0301.11 \n민물의 것 \n완전생산기준 \n \n '}

In [44]:
#csv 저장

import pandas as pd

df = pd.DataFrame(chunks)

df.to_csv(
    "../output/korus_cn_psr_chunks.csv",
    index=False,
    encoding="utf-8-sig"
)

print(df.shape)
df.head()

(5205, 2)

      code                                            content
0  0101.21                      0101.21 \n번식용 \n완전생산기준 \n \n
1  0101.29                       0101.29 \n기타 \n완전생산기준 \n \n
2  0101.30                      0101.30 \n당나귀 \n완전생산기준 \n \n
3  0101.90  0101.90 \n기타 \n완전생산기준 \n \n01.02 \n \n살아 있는 소 ...
4  0102.21                      0102.21 \n번식용 \n완전생산기준 \n \n

In [45]:
df.sample(10)

         code                                            content
657   1510.00  1510.00 \n그 밖의 올리브유와 그 분획물 \n(올리브에서 얻은 것으로서 정제...
2312  4819.50  4819.50 \n그 밖의 포장용기[레코드 슬리브 \n(record sleeve)를...
3414  7205.10  7205.10 \n알갱이 \n4 단위 세번변경기준 \n \n \n \n가루 \n \...
1635  3209.90             3209.90 \n기타 \n4 단위 세번변경기준 \n \n32.10
2565  5403.10  5403.10 \n강력사[비스코스레이온(viscose rayon)의 \n것으로 한정...
4861  9003.11         9003.11 \n플라스틱으로 만든 것 \n4 단위 세번변경기준 \n \n
4652  8536.49  8536.49 \n기타 \n4 단위 세번변경기준 \n또는 체약 당사국내에서 \n발생...
3751  7604.21  7604.21 \n중공(中空)프로파일(profile) \n4 단위 세번변경기준 \n...
4008  8413.50       8413.50 \n그 밖의 용적형 왕복펌프 \n6 단위 세번변경기준 \n \n
4218  8445.13            8445.13 \n연조기나 조방기 \n4 단위 세번변경기준 \n \n